HAI 1.2
CAN HAS STDIO?

VISIBLE "ENTER A NUMBER: "!
I HAS A NUMBER
GIMMEH NUMBER

I HAS A MOD_THREE ITZ MOD OF NUMBER AN 3
I HAS A MOD_FIVE ITZ MOD OF NUMBER AN 5

BOTH SAEM MOD_THREE AN 0
O RLY?
    YA RLY
        BOTH SAEM MOD_FIVE AN 0
        O RLY?
            YA RLY, VISIBLE "FIZZBUZZ"
            NO WAI, VISIBLE "FIZZ"
        OIC

    NO WAI,
        BOTH SAEM MOD_FIVE AN 0
        O RLY?
            YA RLY, VISIBLE "BUZZ"
        OIC
OIC

KTHXBYE